baseURL: 'https://blog.swihal.com'
languageCode: en-us
theme: PaperMod
title: åœ¨äº‘ç«¯



enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: false # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

buildDrafts: false
buildFuture: false
buildExpired: false

paginate: 7 # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°

permalinks:
    post: /:year/:slug/
    page: /:slug/
  # post: "/:title/"
  # post: "/:year/:month/:day/:title/"


Params:
  defaultTheme: auto  # defaultTheme: light or  dark 
  disableThemeToggle: false
  DateFormat: "2006-01-02"
# ShowShareButtons: true
  ShowReadingTime: true
# disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShaowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´
  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  comments: true

  # Home-info mode
  homeInfoParams:
      Title: Hi there ğŸ‘‹
      Content: 
  socialIcons: # optional
  - name: Github
    url: "https://github.com/Gilgamel"
        #- name: "<platform 2>"
        #-   url: "<link2>"


# profile mode (CTRL+/ æ‰¹é‡comment)
# params:
#     profileMode:
#         enabled: false
#         title: "<Title>" # optional default will be site title
#         subtitle: "This is subtitle"
#         imageUrl: "<image link>" # optional
#         imageTitle: "<title of image as alt>" # optional
#         imageWidth: 120 # custom size
#         imageHeight: 120 # custom size
#         #buttons:
#           #  name: Archive
#           #  url: "/archive"
#           #  name: Github
#           #  url: "https://github.com/"

# Add menu
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    #- identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 30
    #- identifier: search
    #  name: Search
    #  url: /search/
    #  weight: 40

# Show search output
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary







